// "Next Token": sung lines with approximate start/end seconds from Whisper words.
// Word timings come from analysis/align.py -> data/lyrics.json.
const LY = [
  [10.5, 13.3, "Type a question, hit enter, now it's gone to the machine,"],
  [13.4, 16.1, "Chopped up into tokens, little pieces that it's seen,"],
  [16.3, 18.8, "It don't see letters, only chunks that it knows,"],
  [19.1, 21.6, "So count the R's in strawberry and watch how it goes,"],
  [21.7, 24.4, "Every token is a vector, four thousand wide,"],
  [24.4, 27.2, "Words that mean the same thing end up side by side,"],
  [27.2, 29.6, "Now the sentence is a stack of numbers standing tall,"],
  [30.2, 33.0, "Thirty-two floors in the tower and it's gotta climb them all"],
  [33.0, 34.9, "Just one more token,"],
  [34.9, 37.7, "One more roll of the dice,"],
  [37.7, 40.7, "Guess it, pick it, feed it back in,"],
  [40.7, 43.0, "And do it again all night"],
  [43.0, 46.4, "Every token looks back at the words that came first,"],
  [46.4, 49.2, "Asks who matters to me, gives a weight to each word,"],
  [49.2, 51.9, "The strongest ones pull and it blends what they say,"],
  [52.1, 55.1, "That's attention, thirty-two heads, each doing it its own way,"],
  [55.1, 57.8, "Then the feed-forward fires where the facts are kept,"],
  [57.8, 60.5, "Fourteen thousand neurons every single step,"],
  [60.5, 62.9, "Attention, feed-forward, that's one floor of the tower,"],
  [62.9, 65.8, "Stack it thirty-two high, that's where it gets its power"],
  [65.8, 68.0, "Just one more token,"],
  [68.0, 70.8, "One more roll of the dice,"],
  [70.8, 73.8, "Guess it, pick it, feed it back in,"],
  [74.3, 76.1, "And do it again all night"],
  [76.1, 79.6, "At the top of the tower every word gets a score,"],
  [81.1, 82.2, "A hundred twenty-eight thousand, all in the draw,"],
  [82.7, 84.8, "Softmax turns them into odds with the temperature set,"],
  [84.8, 87.8, "Keep it low and it's safe, turn it up, it's a bet,"],
  [87.8, 90.5, "Roll the dice, one token, stick it on the end,"],
  [90.7, 93.2, "Feed the whole thing back and do it over again,"],
  [93.2, 96.1, "But the keys and the values that it made, it can keep,"],
  [96.1, 98.8, "That's the K-V cache, so the past comes cheap"],
  [98.8, 101.6, "Every single token, it reads every weight,"],
  [101.6, 104.9, "Sixteen gigs from memory while the math just waits"],
  [115.6, 118.3, "Stuck on the slope, it's the roofline again,"],
  [118.4, 121.0, "So read the weights once and serve a hundred of them,"],
  [121.0, 123.7, "Or a little model guesses four words in a row,"],
  [123.7, 126.4, "And the big one checks all four in one go"],
  [126.4, 128.7, "Just one more token,"],
  [128.7, 131.5, "One more roll of the dice,"],
  [131.5, 134.5, "Guess it, pick it, feed it back in,"],
  [134.5, 136.8, "And do it again all night"],
  [136.8, 139.8, "One more token,"],
  [139.8, 143.0, "Till it picks the one that says it's done"]
];
